name: Pokedex
options:
  bundleIdPrefix: com.michelemola
targets:
  Pokedex:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Pokedex]
    settings:
      TARGETED_DEVICE_FAMILY: 1
